# Generated by Django 4.1.6 on 2024-01-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_material_totales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='totales',
        ),
    ]
